name: triton-distributed-pre-merge-ci
trigger:
  change:
    types: [ create, push ]
    notification:
      when: [ success, failure ]
jobs:
  triton-pre-merge:
    image: hub.byted.org/compile/data.aml.flux_compile:cu124-py311-torch24-241101-3
    envs:
      PYTHONPATH: /home/code/python:/home/code/third_party/nvshmem_bind/python/:$PYTHONPATH
      http_proxy: http://sys-proxy-rd-relay.byted.org:3128
      https_proxy: http://sys-proxy-rd-relay.byted.org:3128
      PATH: /home/code/.local/bin:$PATH
    runs-on:
      cluster: gpu-h100
      docker:
        shared-memory: 1024

    steps:
      - name: code-format-check
        commands:
          - pip3 install ninja black "clang-format==19.1.2" pre-commit ruff yapf==0.43
          - pip3 install pre-commit
          - pre-commit run ruff --from-ref=${{Event.Change.Target.SHA}} --to-ref=${{Event.Change.Source.SHA}} --show-diff-on-failure
          - pre-commit run yapf --from-ref=${{Event.Change.Target.SHA}} --to-ref=${{Event.Change.Source.SHA}} --show-diff-on-failure
          - ./code-format.sh --show-only --fail-on-diff --target ${{Event.Change.Source.SHA}} --base ${{Event.Change.Target.SHA}}

      - name: env-check
        commands:
          - nvidia-smi
          - curl -IivvL https://oaitriton.blob.core.windows.net/public/llvm-builds/
          - mkdir -p /home/code/.local/bin
          - ln -s `which python3` /home/code/.local/bin/python
          - ln -s `which pip3` /home/code/.local/bin/pip
          - hash -r
          - python --version
          - pip --version
          # - pip install -U torch torchvision torchaudio
          - python -c "import torch; print(torch.__version__)"

      - name: build
        commands:
          - git submodule update --init --recursive
          - pip3 install ninja cmake wheel pybind11
          - pip3 wheel -e python --verbose --no-build-isolation
          - mkdir wheel-output
          - mv triton*.whl wheel-output/

      - name: upload wheel
        uses: actions/upload-artifact
        inputs:
          name: release
          path: wheel-output

      - name: triton test
        commands:
          - make dev-install
          - make test

      - name: distributed test
        commands:
          - bash third_party/distributed/distributed/test/run_test.sh
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_all_gather.py