name: triton-distributed-pre-merge-ci
trigger:
  change:
    types: [ create, push ]
    notification:
      when: [ success, failure ]
jobs:
  triton-pre-merge:
    image: hub.byted.org/compile/data.aml.flux_compile:cu124-py311-torch24-241101-3
    envs:
      PYTHONPATH: /home/code/python:/home/code/third_party/nvshmem_bind/python/:$PYTHONPATH
      LD_LIBRARY_PATH: /home/code/third_party/nvshmem/build/install/lib:$LD_LIBRARY_PATH
      http_proxy: http://sys-proxy-rd-relay.byted.org:3128
      https_proxy: http://sys-proxy-rd-relay.byted.org:3128
      PATH: /home/code/.local/bin:$PATH
    runs-on:
      cluster: gpu-h100
      docker:
        shared-memory: 1024

    steps:
      - name: code-format-check
        commands:
          - pip3 install ninja black "clang-format==19.1.2" pre-commit ruff yapf==0.43
          - pip3 install cuda-python==12.4
          - pip3 install pytest
          - pip3 install chardet
          - pre-commit run ruff --from-ref=${{Event.Change.Target.SHA}} --to-ref=${{Event.Change.Source.SHA}} --show-diff-on-failure
          - pre-commit run yapf --from-ref=${{Event.Change.Target.SHA}} --to-ref=${{Event.Change.Source.SHA}} --show-diff-on-failure
          - ./code-format.sh --show-only --fail-on-diff --target ${{Event.Change.Source.SHA}} --base ${{Event.Change.Target.SHA}}
          - python3 scripts/check_license.py

      - name: env-check
        commands:
          - nvidia-smi
          - curl -IivvL https://oaitriton.blob.core.windows.net/public/llvm-builds/
          - mkdir -p /home/code/.local/bin
          - ln -s `which python3` /home/code/.local/bin/python
          - ln -s `which pip3` /home/code/.local/bin/pip
          - hash -r
          - python3 --version
          - pip3 --version
          - python3 -c "import torch; print(torch.__version__)"

      - name: build
        commands:
          - git submodule update --init --recursive
          - pip3 install ninja cmake wheel pybind11
          - export USE_TRITON_DISTRIBUTED_AOT=0
          - MAX_JOBS=126 pip3 install -e python --verbose --no-build-isolation
          - bash ./scripts/gen_aot_code.sh
          - export USE_TRITON_DISTRIBUTED_AOT=1
          - MAX_JOBS=126 pip3 install -e python --verbose --no-build-isolation

      - name: distributed tests
        commands:
          #############
          # ad-hoc test
          #############
          # basic
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_distributed_wait.py --case correctness
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_distributed_wait.py --case correctness_tma
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_distributed_wait.py --case correctness_tma_multi_barrier
          # ag gemm
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_ag_gemm_intra_node.py --case correctness_tma
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_ag_gemm_intra_node.py --case correctness_tma_autotune

          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_ag_gemm_inter_node.py --M 8192
          # gemm rs
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_gemm_rs_multi_node.py 8192 8192 29568
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_gemm_rs_multi_node.py 8192 8192 29568 --check
          # allgather
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_ag_small_msg.py
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_all_gather.py
          - bash -x ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_fast_allgather.py   --iters 10   --warmup_iters 20   --mode push_2d_ll   --minbytes 4096   --maxbytes 8192
          # all-to-all
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_all_to_all.py
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_ep_moe_inference.py
          # nvshmem related
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_nvshmem_api.py
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_ring_put.py
          # flash decoding
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_decode_attn.py --case perf_8k
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_decode_attn.py --case perf_8k_persistent
          - USE_TRITON_DISTRIBUTED_AOT=1 bash ./third_party/distributed/launch.sh  ./third_party/distributed/distributed/test/test_decode_attn.py --case perf_8k_persistent_aot
          - USE_TRITON_DISTRIBUTED_AOT=1 bash ./third_party/distributed/launch.sh  ./third_party/distributed/distributed/test/test_decode_attn.py --case perf_8k_aot
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_sp_decode_attn.py --case perf
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_sp_decode_attn.py --case correctness
          - USE_TRITON_DISTRIBUTED_AOT=1 bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_sp_decode_attn.py --case correctness
          # ag moe
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_ag_moe.py --M 2048
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_ag_moe.py --M 4096
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_ag_moe.py --M 8192
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_ag_moe.py --M 16384
          # moe rs
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_moe_reduce_rs_intra_node.py 8192 2048 1536 32 2
          - bash ./third_party/distributed/launch.sh ./third_party/distributed/distributed/test/test_moe_reduce_rs_intra_node.py 8192 2048 1536 32 2 --check
          #############
          # pytest (disabled)
          #############
          # flash decoding
          # - pytest ./third_party/distributed/distributed/test/test_decode_attn.py::test_triton_decode_with_paged_kv
          # - pytest ./third_party/distributed/distributed/test/test_decode_attn.py::test_triton_decode_with_paged_kv_persistent
          # - USE_TRITON_DISTRIBUTED_AOT=1 pytest ./third_party/distributed/distributed/test/test_decode_attn.py::test_triton_decode_with_paged_kv_persistent_aot
